name: Deploy to Azure Function App

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          environment: azurecloud
          tenant-id: "34916e8d-6ece-4734-b11a-a636d7d30ba3"
          client-id: "0087c21e-4621-4072-a7d9-77aac642d8bf"
          principal-id: "ec6dc8ca-d5ff-403a-907a-1f2d23bdd6e0"
          enable-AzPSSession: false
          allow-no-subscriptions: false
          audience: api://AzureADTokenExchange
          auth-type: SERVICE_PRINCIPAL

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Azure Function App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.GroundZeroMV }}
          slot-name: production
          publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE }}
          package: ./functions.zip



