name: Deploy to Azure Function App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        tenant-id: 34916e8d-6ece-4734-b11a-a636d7d30ba3
        client-id: 55795fe6-ab23-401a-8e68-9e239c5ecc9a
        subscriptionId: YOUR_SUBSCRIPTION_ID_HERE
        enable-AzPSSession: false
        environment: azurecloud
        allow-no-subscriptions: false
        audience: api://AzureADTokenExchange

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Azure Function App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.GroundZeroMV }}
          slot-name: production
          publish-profile: ${{ secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE }}
          package: ./functions.zip


